
# Dockerfile to build frontend that uses nginx as web server

# Use nginx as base image
FROM nginx:alpine

# Copy static files into container
COPY . /usr/share/nginx/html

# Exposes port 80 inside the container
EXPOSE 80