
openapi: 3.0.0
info:
  title: API
  version: 1.1.0
  description: Swagger API Documentation

servers: 
  - url: http://localhost:5000

tags:
  - name: Users 
    description: Endpoints for user registration and authentication.
  - name: Comics 
    description: Endpoints for managing comic collection and data.

paths:
  # Comic related routes
  /comics:
    # Get all comics
    get:
      tags: 
        - Comics
      summary: Get all comics
      responses:
        '200':
          description: A list of all saved comics
    
    # Add a comic
    post:
      tags: 
        - Comics
      summary: Create a new comic
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
                - author
                - issue
                - volume
              properties:
                title:
                  type: string
                author: 
                  type: string
                issue:
                  type: number
                  minimum: 1
                volume:
                  type: number
                  minimum: 1
                publisher:
                  type: string
                coverVariant:
                  type: string
                releaseDate:
                  type: string
                  format: date
                rating:
                  type: number
                  minimum: 1
                  maximum: 10
                purchasePrice:
                  type: number
                currentValue:
                  type: number
                condition:
                  type: string
                  enum: 
                    - Near Mint
                    - Very Fine
                    - Fine
                    - Very Good
                    - Good
                    - Fair
                    - Poor
                  default: Good
                isRead:
                  type: boolean
                  default: false
                genre:
                  type: string
                tags:
                  type: array
                  items:
                    type: string
                notes:
                  type: string
      responses:
        '201':
          description: Comic created

  # GET a comic by id
  /comics/{id}:
    get:
      tags: 
        - Comics
      summary: Retreive a Comic by ID
      description: Returns a single comic object based on the provided ID.
      parameters:
        - in: path
          name: id
          required: true
          schema: 
            type: string
          description: The ID of the Comic to retreive
      responses:
        '200':
          description: Comic by ID
        '404':
          description: Comic not found

  # User register route
  /users/register:
    post:
      tags: 
        - Users
      summary: Register a new user
      requestBody:
        required: true
        content: 
          application/json:
            schema:
              type: object
              required: 
                - username
                - email
                - password
              properties:
                username: 
                  type: string
                email:
                  type: string
                password: 
                  type: string
      responses:
        '201':
          description: User created
        '400':
          description: Request related error

  # User login route
  /users/login:
    post:
      tags: 
        - Users
      summary: Login to your account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password 
              properties:
                email:
                  type: string
                password: 
                  type: string 
      responses:
        '200':
          description: Login Successful!
        '400':
          description: Bad request - missing or invalid parameters
        '401':
          description: Unauthorized - incorrect email or password